[package]
name = "solana_vault"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = { version = "0.29.0", features = ["init-if-needed"]}
anchor-spl = { version = "0.29.0", features = ["associated_token"] }

[lib]
crate-type = ["cdylib", "lib"]
