[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_nft_minting = "GXFZLamQc3tELeRYeoVX88uthLCC12j7NRFkyCSXcDwd"
solana_swap = "AT1rUerisJ8vproAoX5ic93EGgGfBGyF1izobFuAgndN"
solana_vault = "EZSkMDXfzCmy4n7sJoesYCoacANCcJvit5R5QDJ9m5rT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/pradip/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
